/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mixi.form;

import Entities.TaiKhoan;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import nhom4.ConnectDB;

/**
 *
 * @author admin
 */
public class frmDangNhap extends javax.swing.JFrame {

    ArrayList<TaiKhoan> dstk = new ArrayList<>();

    /**
     * Creates new form DangNhap
     */
    public frmDangNhap() {
        new ConnectDB().getListTK();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTk = new javax.swing.JTextField();
        butDangNhap = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ĐĂNG NHẬP VÀO SHOP MIXI!!!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel2.setText("Tài khoản:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jLabel3.setText("Mật khẩu:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        txtTk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTkActionPerformed(evt);
            }
        });
        getContentPane().add(txtTk, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 170, -1));

        butDangNhap.setText("Đăng nhập");
        butDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butDangNhapMouseClicked(evt);
            }
        });
        butDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(butDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 110, -1));
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 170, -1));

        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butDangNhapMouseClicked
//        this.dispose();
//        new frmTrangChuAdmin().setVisible(true);
    }//GEN-LAST:event_butDangNhapMouseClicked

    private void txtTkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTkActionPerformed

    private void butDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDangNhapActionPerformed

 
        String id = txtTk.getText();
        String pass = txtPass.getText();
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Tài khoản không được để trống");
            return;
        }
        if (pass.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Mật khẩu không được để trống");
            return;
        }
        if (new ConnectDB().checkTk(id, pass)) {
             JOptionPane.showMessageDialog(rootPane, "Đăng nhập thành công!"); 
            new frmTrangChuAdmin().setVisible(true);
            this.hide();
        } else{
            JOptionPane.showMessageDialog(rootPane, "Đăng nhập thất bại!"); 
            //new frmTrangChuNV().setVisible(true);this.hide();
         
        }
    }//GEN-LAST:event_butDangNhapActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDangNhap().setVisible(true);
//                DangNhap d = new DangNhap();
//                d.setLocation(null);
//                d.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butDangNhap;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtTk;
    // End of variables declaration//GEN-END:variables
}
