/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mixi.form;

import Entities.HoaDonBanHang;
import Entities.KhachHang;
import Entities.NhanVien;
import Entities.TaiKhoan;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import nhom4.ConnectDB;

/**
 *
 * @author ADMIN
 */
public class frmQuanLiHoaDonBanHang extends javax.swing.JFrame {

    DefaultTableModel tableHD;

    /**
     * Creates new form QuanLiDonHang
     */
    public frmQuanLiHoaDonBanHang() {

        initComponents();
        setLocationRelativeTo(null);
       

        loadcbb("SELECT * FROM NHANVIEN", jComboBoxTennv, "TENNHANVIEN");
        loadcbb("SELECT * FROM KHACHHANG", jComboBoxTenkh, "TENKHACHHANG");
        loadcbb("SELECT * FROM SANPHAM", cbbTensp, "TENSANPHAM");
//        getData();
        LayDuLieuHoaDon();

    }
    Calendar cal = Calendar.getInstance();

    int day = cal.get(Calendar.DAY_OF_MONTH);
    int month = cal.get(Calendar.MONTH) + 1;
    int year = cal.get(Calendar.YEAR);

    Date dt = cal.getTime();
// Dinh dang lai hien thi thong tin ngay gio ra man hinh
    SimpleDateFormat fm = new SimpleDateFormat("dd-MM-yyyy");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCTHD = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMahd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jButtonThem = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jComboBoxTenkh = new javax.swing.JComboBox<>();
        jComboBoxTennv = new javax.swing.JComboBox<>();
        cbbngay = new javax.swing.JComboBox<>();
        cbbthang = new javax.swing.JComboBox<>();
        cbbnam = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableHD = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtMacthd = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtSl = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtThanhtien = new javax.swing.JTextField();
        jButtonThem2 = new javax.swing.JButton();
        jButtonSua2 = new javax.swing.JButton();
        jButtonXoa2 = new javax.swing.JButton();
        cbbTensp = new javax.swing.JComboBox<>();
        txtMahd2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí hóa đơn");
        setName("quanlidonhang"); // NOI18N
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jTableCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mãchi tiết HD", "Mã hóa đơn", "Tên sản phẩm", "Số lượng", "Thành tiền"
            }
        ));
        jTableCTHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCTHDMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCTHD);
        if (jTableCTHD.getColumnModel().getColumnCount() > 0) {
            jTableCTHD.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        jLabel1.setText("Mã hóa đơn");

        txtMahd.setEditable(false);

        jLabel2.setText("Tên nhân viên");

        jLabel3.setText("Tên khách hàng");

        jLabel4.setText("Ngày lập");

        jLabel7.setText("Tổng tiền");

        txtTongTien.setEditable(false);

        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        jButtonSua.setText("Sửa");
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });

        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });

        jComboBoxTenkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTenkhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMahd)
                            .addComponent(jComboBoxTenkh, 0, 123, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jButtonThem, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jButtonSua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonXoa))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cbbngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbbthang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbbnam, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBoxTennv, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBoxTenkh, txtMahd, txtTongTien});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonSua, jButtonThem, jButtonXoa});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMahd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxTenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxTennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbbngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbthang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbnam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThem)
                    .addComponent(jButtonSua)
                    .addComponent(jButtonXoa))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTableHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn ", "Tên khách hàng", "Tên nhân viên", "Ngày lập", "Tổng tiền"
            }
        ));
        jTableHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHDMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableHD);
        if (jTableHD.getColumnModel().getColumnCount() > 0) {
            jTableHD.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        jLabel11.setText("Mã chi tiết HD");

        txtMacthd.setEditable(false);

        jLabel12.setText("Sản phẩm");

        jLabel13.setText("Mã hóa đơn");

        jLabel14.setText("Số lượng");

        jLabel15.setText("Thành tiền");

        txtThanhtien.setEditable(false);

        jButtonThem2.setText("Thêm");
        jButtonThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThem2ActionPerformed(evt);
            }
        });

        jButtonSua2.setText("Sửa");
        jButtonSua2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSua2ActionPerformed(evt);
            }
        });

        jButtonXoa2.setText("Xóa");
        jButtonXoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoa2ActionPerformed(evt);
            }
        });

        txtMahd2.setEditable(false);

        jButton1.setText("Trở lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonThem2)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSua2)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonXoa2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtThanhtien, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(txtSl, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(cbbTensp, 0, 82, Short.MAX_VALUE)
                            .addComponent(txtMacthd, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(txtMahd2))))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbbTensp, txtMacthd, txtSl, txtThanhtien});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel11, jLabel12, jLabel13});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonSua2, jButtonThem2, jButtonXoa2});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMacthd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtMahd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbbTensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtSl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtThanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThem2)
                    .addComponent(jButtonSua2)
                    .addComponent(jButtonXoa2)
                    .addComponent(jButton1))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel3, jPanel4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jTableCTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCTHDMouseClicked
        int vitri = jTableCTHD.getSelectedRow();
        System.out.println(vitri);
        txtMacthd.setText(jTableCTHD.getValueAt(vitri, 0).toString());
        txtMahd2.setText(jTableCTHD.getValueAt(vitri, 1).toString());
        cbbTensp.setSelectedItem(jTableCTHD.getValueAt(vitri, 2).toString());
        txtSl.setText(jTableCTHD.getValueAt(vitri, 3).toString());
        txtThanhtien.setText(jTableCTHD.getValueAt(vitri, 4).toString());


    }//GEN-LAST:event_jTableCTHDMouseClicked

    private void jTableHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHDMouseClicked

        int vitri = jTableHD.getSelectedRow();
        System.out.println(vitri);
        
        txtMahd.setText(jTableHD.getValueAt(vitri, 0).toString());
        
        txtTongTien.setText(jTableHD.getValueAt(vitri, 4).toString());
        jComboBoxTenkh.setSelectedItem(jTableHD.getValueAt(vitri, 1).toString());
        jComboBoxTennv.setSelectedItem(jTableHD.getValueAt(vitri, 2).toString());
        txtMahd2.setText(jTableHD.getValueAt(vitri, 0).toString());
        LayDuLieuChiTietHoaDon(jTableHD.getValueAt(vitri, 0).toString());
    }//GEN-LAST:event_jTableHDMouseClicked

    private void jComboBoxTenkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTenkhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTenkhActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        int mahd = Integer.parseInt(txtMahd.getText());
        String sql = "delete HoaDon where MaHoaDon=" + mahd + "";
        new ConnectDB().ExcuteQueryGetTable(sql);
        LayDuLieuHoaDon();
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
        String tenKH, tenNV;
        int mahd = Integer.parseInt(txtMahd.getText());
        tenKH = jComboBoxTenkh.getSelectedItem().toString();
        tenNV = jComboBoxTennv.getSelectedItem().toString();
        String sql1 = "select MaKhachHang from KhachHang where TenKhachHang = N'" + tenKH + "'";
        String sql2 = "select MaNhanVien from NhanVien where TenNhanVien =N'" + tenNV + "'";
        ResultSet rs1 = new ConnectDB().ExcuteQueryGetTable(sql1);
        ResultSet rs2 = new ConnectDB().ExcuteQueryGetTable(sql2);
        int makh = 0, manv = 0;
        try 
        {
           while (rs1.next())
           {
                makh = rs1.getInt("MaKhachHang");
            }

        } catch (Exception e)
        {
            e.printStackTrace();
        }
        try 
        {
            while (rs2.next())
            {
                manv = rs2.getInt("MaNhanVien");
            }

        } catch (Exception e)
        {
        }
        String sql = "update HoaDon set MaKhachHang=" + makh + ",MaNhanVien=" + manv + " where MaHoaDon=" + mahd + "";
        new ConnectDB().ExcuteQueryUpdateDB(sql);
        LayDuLieuHoaDon();
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        String tenKH, tenNV;
        tenKH = jComboBoxTenkh.getSelectedItem().toString();
        tenNV = jComboBoxTennv.getSelectedItem().toString();
        String sql1 = "select MaKhachHang from KhachHang where TenKhachHang = N'" + tenKH + "'";
        String sql2 = "select MaNhanVien from NhanVien where TenNhanVien = N'" + tenNV + "'";
       
        ResultSet rs1 = new ConnectDB().ExcuteQueryGetTable(sql1);
        ResultSet rs2 = new ConnectDB().ExcuteQueryGetTable(sql2);
        int makh = 0, manv = 0;
        
        try {
            while (rs1.next()) {
                makh = rs1.getInt("MaKhachHang");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            while (rs2.next()) {
                manv = rs2.getInt("MaNhanVien");
            }

        } catch (Exception e) {

        }
        String ngay, thang, nam;
        ngay = cbbngay.getSelectedItem().toString();
        thang = cbbthang.getSelectedItem().toString();
        nam = cbbnam.getSelectedItem().toString();
        String NgayLap = ngay + "-"+ thang + "-" + nam;
        System.out.println("Ngày"+NgayLap);
        String cautruyvan = "insert into HoaDon(MaKhachHang,MaNhanVien,ngaylaphoadon,TongTien) values(  '" + makh + "','" + manv + "','" + NgayLap + "','" + 0 + "')";
        new ConnectDB().ExcuteQueryUpdateDB(cautruyvan);
        System.out.println("Đã Thêm Thành Công");
        LayDuLieuHoaDon();
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtonThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThem2ActionPerformed
        String tensp;
        int mahd, sl;
        float tongtien = 0;
        mahd = Integer.parseInt(txtMahd2.getText());
        sl = Integer.parseInt(txtSl.getText());
        tensp = cbbTensp.getSelectedItem().toString();
        String sql1 = "select giaban from SanPham where TenSanPham = N'" + tensp + "'";
        String sql2 = "select MaSanPham from SanPham where TenSanPham = N'" + tensp + "'";
        String sql3 = "select sum(tongtien) as thanhtien from ChiTietHoaDon where MaHoaDon='" + txtMahd.getText() + "'";
        ResultSet rs3 = new ConnectDB().ExcuteQueryGetTable(sql3);
        ResultSet rs1 = new ConnectDB().ExcuteQueryGetTable(sql1);
        ResultSet rs2 = new ConnectDB().ExcuteQueryGetTable(sql2);
        int masp = 0;
        float gia = 0;
        System.out.println(tensp);

        try
        {
            while (rs1.next())
            {

                gia = rs1.getFloat("giaban");
            }

        } catch (Exception e)
        {
            e.printStackTrace();
        }

        try 
        {
            while (rs2.next())
            {
                masp = rs2.getInt("MaSanPham");
                System.out.println("máp" + rs2.getInt("MaSanPham"));

            }

        } catch (Exception e)
        {

        }

        try 
        {
            while (rs3.next())
            {
               tongtien = rs3.getFloat("thanhtien");

            }
        } catch (Exception e)
        {
            e.printStackTrace();
        }
        System.out.println("Tong"+tongtien);
        float thanhtien = sl * gia;
        String sql = "insert into ChiTietHoaDon(MaHoaDon,MaSanPham,soluong,TongTien) values(  '" + mahd + "','" + masp + "','" + sl + "','" + thanhtien + "')";
        new ConnectDB().ExcuteQueryUpdateDB(sql);  
                new ConnectDB().ExcuteQueryUpdateDB("update HoaDon set tongtien='" + (tongtien+thanhtien) + "' where MaHoaDon='" + txtMahd2.getText() + "'");

        System.out.println("Đã Thêm Thành Công");
        LayDuLieuChiTietHoaDon(txtMahd2.getText());
        LayDuLieuHoaDon();
        
    }//GEN-LAST:event_jButtonThem2ActionPerformed

    private void jButtonSua2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSua2ActionPerformed
        String tensp;
        int mahd, sl,macthd;
        float tongtien = 0;
        macthd=Integer.parseInt(txtMacthd.getText());
        mahd = Integer.parseInt(txtMahd2.getText());
        sl = Integer.parseInt(txtSl.getText());
        tensp = cbbTensp.getSelectedItem().toString();
        String sql1 = "select giaban from SanPham where TenSanPham = N'" + tensp + "'";
        String sql2 = "select MaSanPham from SanPham where TenSanPham = N'" + tensp + "'";
        String sql3 = "select sum(tongtien) as thanhtien from ChiTietHoaDon where MaHoaDon='" + txtMahd.getText() + "'";
        
        ResultSet rs1 = new ConnectDB().ExcuteQueryGetTable(sql1);
        ResultSet rs2 = new ConnectDB().ExcuteQueryGetTable(sql2);
        ResultSet rs3 = new ConnectDB().ExcuteQueryGetTable(sql3);
        int masp = 0;
        float gia = 0;
        System.out.println(tensp);

        try {
            while (rs1.next()) {

                gia = rs1.getFloat("giaban");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        try {
            while (rs2.next()) {
                masp = rs2.getInt("MaSanPham");
                System.out.println("máp" + rs2.getInt("MaSanPham"));

            }

        } catch (Exception e) {

        }

        try {
            while (rs3.next()) {
                tongtien = rs3.getFloat("thanhtien");

            }
        } catch (Exception e) {

        }
        float thanhtien = sl * gia;
        String sql = "update ChiTietHoaDon set MaHoaDon=" + mahd + ",MaSanPham=" + masp + ",soluong=" + sl + ",TongTien=" + thanhtien + " where MaCTHD="+macthd+"";
        new ConnectDB().ExcuteQueryUpdateDB(sql);
        System.out.println("Đã sửa Thành Công");

        new ConnectDB().ExcuteQueryUpdateDB("update HoaDon set tongtien='" + tongtien + "' where MaHoaDon='" + txtMahd2.getText() + "'");
        LayDuLieuChiTietHoaDon(txtMahd2.getText());
        LayDuLieuHoaDon();
    }//GEN-LAST:event_jButtonSua2ActionPerformed

    private void jButtonXoa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoa2ActionPerformed
        
        
        int sl,macthd;
        float tongtien = 0;
        macthd=Integer.parseInt(txtMacthd.getText());
        sl = Integer.parseInt(txtSl.getText());
        String tensp = cbbTensp.getSelectedItem().toString();
        String sql2 = "select giaban from SanPham where TenSanPham = N'" + tensp + "'";
        String sql = "select sum(tongtien) as thanhtien from ChiTietHoaDon where MaHoaDon='" + txtMahd.getText() + "'";
        ResultSet rs = new ConnectDB().ExcuteQueryGetTable(sql);
        ResultSet rs1 = new ConnectDB().ExcuteQueryGetTable(sql2);
        float gia = 0;
        System.out.println(tensp);

        try {
            while (rs1.next()) {

                gia = rs1.getFloat("giaban");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            while (rs.next()) {
                tongtien = rs.getFloat("thanhtien");

            }
        } catch (Exception e) {

        }
        float thanhtien = sl * gia;
        float t=tongtien-thanhtien;
        System.out.println("â"+thanhtien);
        String sql1 = "delete ChiTietHoaDon where MaCTHD="+macthd+"";
        new ConnectDB().ExcuteQueryUpdateDB(sql1);
        System.out.println("Đã sửa Thành Công");
        new ConnectDB().ExcuteQueryUpdateDB("update HoaDon set tongtien='" + (tongtien-thanhtien) + "' where MaHoaDon='" + txtMahd2.getText() + "'");
        LayDuLieuChiTietHoaDon(txtMahd2.getText());
        LayDuLieuHoaDon() ;
    }//GEN-LAST:event_jButtonXoa2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new frmTrangChuAdmin().setVisible(true);
this.hide();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        DefaultComboBoxModel cbbmodel = new DefaultComboBoxModel();

        for (int i = 1; i < 32; i++) {
            cbbngay.addItem(String.valueOf(i));
        }
        for (int i = 1; i < 13; i++) {
            cbbthang.addItem(String.valueOf(i));
        }
        for (int i = year; i > 1980; i--) {
            cbbnam.addItem(String.valueOf(i));
        }
        cbbnam.setSelectedItem(String.valueOf(year));
        cbbngay.setSelectedItem(String.valueOf(day));
        cbbthang.setSelectedItem(String.valueOf(month));
    }//GEN-LAST:event_formComponentShown
    public void LayDuLieuHoaDon() {

        String sql = "select MaHoaDon,KhachHang.TenKhachHang as TenKhachHang,NhanVien.TenNhanVien as TenNhanVien,TongTien,NgayLapHoaDon from HoaDon,KhachHang,NhanVien where HoaDon.MaKhachHang =KhachHang.MaKhachHang "
                + "and HoaDon.MaNhanVien=NhanVien.MaNhanVien ";
        ResultSet rs = new ConnectDB().ExcuteQueryGetTable(sql);
        Object[] obj = new Object[]{"Mã hóa đơn", "Tên Khách Hàng ", "Tên Nhân viên", "Ngày lập", "tổng Tiền"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        jTableHD.setModel(tableModel);

        try {
            while (rs.next()) {
                Object[] item = new Object[6];
                item[0] = rs.getInt("MaHoaDon");
                item[1] = rs.getString("TenKhachHang");
                item[2] = rs.getString("TenNhanVien");
                item[3] = rs.getString("NgayLapHoaDon");
                item[4] = rs.getInt("TongTien");
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }

    }

    public void loadcbb(String sql, JComboBox cbb, String bien) {
        try {
            Connection cn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=QuanLySanPhamMixiShop", "sa", "123456");

            PreparedStatement ps = cn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {

                cbb.addItem(rs.getString(bien));
            }

        } catch (SQLException ex) {

        }
//        
    }

    public void LayDuLieuChiTietHoaDon(String MaHoaDon) {
        String cautruyvan = "select MaCTHD,MaHoaDon,SanPham.TenSanPham,SoLuong,TongTien "
                + " from ChiTietHoaDon,SanPham where ChiTietHoaDon.MaSanPham=SanPham.MaSanPham  and MaHoaDon=" + MaHoaDon;
        ResultSet rs = new ConnectDB().ExcuteQueryGetTable(cautruyvan);
        Object[] obj = new Object[]{"Mã CTHD", "Mã Hóa Đơn", "Sản Phẩm", "Số Lượng", "Thành tiền"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        jTableCTHD.setModel(tableModel);
        try {
            while (rs.next()) {

                Object[] item = new Object[5];

                item[0] = rs.getInt("MaCTHD");
                item[1] = rs.getString("MaHoaDon");
                item[2] = rs.getString("TenSanPham");
                item[3] = rs.getString("SoLuong");
                item[4] = rs.getDouble("TongTien");

                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQuanLiHoaDonBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQuanLiHoaDonBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQuanLiHoaDonBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQuanLiHoaDonBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQuanLiHoaDonBanHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbTensp;
    private javax.swing.JComboBox<String> cbbnam;
    private javax.swing.JComboBox<String> cbbngay;
    private javax.swing.JComboBox<String> cbbthang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonSua2;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonThem2;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JButton jButtonXoa2;
    private javax.swing.JComboBox<String> jComboBoxTenkh;
    private javax.swing.JComboBox<String> jComboBoxTennv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableCTHD;
    private javax.swing.JTable jTableHD;
    private javax.swing.JTextField txtMacthd;
    private javax.swing.JTextField txtMahd;
    private javax.swing.JTextField txtMahd2;
    private javax.swing.JTextField txtSl;
    private javax.swing.JTextField txtThanhtien;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables

}
