/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mixi.form;

import Entities.NhanVien;
import Entities.PhieuNhap;
import Entities.SanPham;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ComboBox;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.DatatypeConverter;
import nhom4.ConnectDB;

/**
 *
 * @author ADMIN
 */
public class QuanLiSanPham extends javax.swing.JFrame {

    ArrayList<SanPham> dssp = new ArrayList<>();
    DefaultTableModel tableSP;
//    ArrayList<PhieuNhap> dspn = new ArrayList<>();
//    DefaultTableModel tablePN;
    
    /**
     * Creates new form QuanLiSanPham
     */
    public QuanLiSanPham() {
        initComponents();
        this.setLocationRelativeTo(null);
//        getData();
//        getDataPN();
        loadDataCbb("SELECT * FROM NHACUNGCAP",cbbNhaCC, "TENNHACUNGCAP");
        loadDataCbb("SELECT * FROM NHANVIEN", cbbNhanVien, "TENNHANVIEN");
        loadDataCbb("SELECT * FROM SANPHAM", cbbSanPham, "TENSANPHAM");
        LayDuLieuPhieuNhap();    
        getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneSanPham = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableQlsp = new javax.swing.JTable();
        txtMasp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTensp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        jButtonThem = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSoluongcon = new javax.swing.JTextField();
        cbbThuongHieu = new javax.swing.JComboBox<>();
        btnReload = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePhieuNhap = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCTPhieuNhap = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtMapn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbbNhanVien = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jButtonThemP = new javax.swing.JButton();
        jButtonSuaP = new javax.swing.JButton();
        jButtonXoaP = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtMaCtpn = new javax.swing.JTextField();
        cbbSanPham = new javax.swing.JComboBox<>();
        txtMaPN_CTPN = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtThanhTien = new javax.swing.JTextField();
        jButtonThemCt = new javax.swing.JButton();
        jButtonSuaCT = new javax.swing.JButton();
        jButtonXoaCT = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        cbbNhaCC = new javax.swing.JComboBox<>();
        txtNgayNhap = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí sản phẩm");
        setName("quanlisanpham"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPaneSanPham.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPaneSanPhamComponentShown(evt);
            }
        });

        jTableQlsp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Thương hiệu", "Giá nhập", "Giá bán", "Số lượng còn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableQlsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableQlspMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableQlsp);

        txtMasp.setEditable(false);

        jLabel1.setText("Mã sản phẩm");

        jLabel2.setText("Tên sản phẩm");

        jLabel4.setText("Giá nhập");

        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        jButtonSua.setText("Sửa");
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });

        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });

        jButtonBack.setText("Trở lại");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabel6.setText("Giá bán");

        jLabel7.setText("Thương hiệu");

        jLabel8.setText("Số lượng còn");

        cbbThuongHieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gucci", "Channel", "Louis Vuitton", "Armani", "Fendi", "House of Versace", "Burberry", "Ralph Lauren", "Prada", "Hermes", "Khác" }));

        btnReload.setText("Tải lại");
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMasp, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoluongcon, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonBack, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReload, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonThem)
                            .addComponent(jButtonSua)
                            .addComponent(jButtonXoa))))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbbThuongHieu, txtGiaBan, txtGiaNhap, txtMasp, txtSoluongcon, txtTensp});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonSua, jButtonThem, jButtonXoa});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(txtMasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonThem))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jButtonSua))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonXoa)
                            .addComponent(jButtonBack))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReload)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbbThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(txtSoluongcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jTabbedPaneSanPham.addTab("Danh sách sản phẩm", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã  PN", "Tên nhân viên nhập", "Tên nhà cung cấp", "Ngày nhập", "Tổng tiềnđ"
            }
        ));
        jTablePhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePhieuNhapMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePhieuNhap);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 32, 581, 170));

        jTableCTPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã chi tiết phiếu nhập", "Mã phiếu nhập", "Tên sản phẩm", "Số lượng", "Thành tiền"
            }
        ));
        jTableCTPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCTPhieuNhapMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableCTPhieuNhap);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 261, 581, 168));

        jLabel3.setText("Mã phiếu nhập");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        txtMapn.setEditable(false);
        jPanel2.add(txtMapn, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 23, 188, -1));

        jLabel5.setText("Nhân viên");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, -1, -1));

        jPanel2.add(cbbNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 58, 188, -1));

        jLabel9.setText("Nhà cung cấp ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 98, -1, -1));

        jLabel10.setText("Tổng tiền");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 134, -1, -1));

        txtTongTien.setEditable(false);
        txtTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienActionPerformed(evt);
            }
        });
        jPanel2.add(txtTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 128, 188, -1));

        jButtonThemP.setText("Thêm");
        jButtonThemP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemPActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonThemP, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 198, 79, -1));

        jButtonSuaP.setText("Sửa");
        jButtonSuaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaPActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSuaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 198, 79, -1));

        jButtonXoaP.setText("Xóa");
        jButtonXoaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaPActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonXoaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 198, 79, -1));

        jLabel11.setText("Mã chi tiết phiếu nhập");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 254, -1, -1));

        jLabel12.setText("Mã phiếu nhập");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 298, -1, -1));

        jLabel13.setText("Sản phẩm");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 342, -1, -1));

        jLabel14.setText("Số lượng");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 386, -1, -1));

        jLabel15.setText("Thành tiền");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 430, -1, -1));

        txtMaCtpn.setEditable(false);
        jPanel2.add(txtMaCtpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 251, 188, -1));

        jPanel2.add(cbbSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 339, 188, -1));

        txtMaPN_CTPN.setEditable(false);
        jPanel2.add(txtMaPN_CTPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 295, 188, -1));
        jPanel2.add(txtSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 383, 188, -1));

        txtThanhTien.setEditable(false);
        jPanel2.add(txtThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 427, 188, -1));

        jButtonThemCt.setText("Thêm");
        jButtonThemCt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemCtActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonThemCt, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 484, 79, -1));

        jButtonSuaCT.setText("Sửa");
        jButtonSuaCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaCTActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSuaCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 484, 79, -1));

        jButtonXoaCT.setText("Xóa");
        jButtonXoaCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaCTActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonXoaCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 484, 79, -1));

        jButton2.setText("Trở lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, -1, -1));

        jLabel16.setText("Ngày nhập");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 166, -1, -1));
        jPanel2.add(cbbNhaCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 93, 188, -1));

        txtNgayNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayNhapActionPerformed(evt);
            }
        });
        jPanel2.add(txtNgayNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 163, 188, -1));

        jTabbedPaneSanPham.addTab("Phiếu nhập sản phẩm", jPanel2);

        getContentPane().add(jTabbedPaneSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1050, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        new frmTrangChuAdmin().setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButtonBackActionPerformed

    public void loadDataCbb(String sql, JComboBox cbb, String tenBien){
        
        try {
            
//            String sql = "select * from NHACUNGCAP";
            Connection cn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=QuanLySanPhamMixiShop", "sa", "123456");
            try {
                PreparedStatement ps = cn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                while (rs.next()){
                    cbb.addItem(rs.getString(tenBien));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e, "Thông báo lỗi", 1);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLiSanPham.class.getName()).log(Level.SEVERE,null, ex);
            
        }
    }
    
       public void LayDuLieuSanPham() {
           try {
               Connection cn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=QuanLySanPhamMixiShop", "sa", "123456");
               try {
                   String sql = "";
                   sql = "select * from SanPham";
                   
                   PreparedStatement ps = cn.prepareStatement(sql);
                   ResultSet rs = ps.executeQuery();
                   Object[] obj = new Object[]{"Mã sản phẩm", "Tên sản phẩm", "Thương hiệu", "Giá nhập", "Giá bán", "Số lượng còn"};
                   DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
                   jTableQlsp.setModel(tableModel);
                   System.out.println("Kết nối ok");
                   try {
                       while (rs.next()) {
                           Object[] item = new Object[6];
                           item[0] = rs.getInt("MASANPHAM");
                           item[1] = rs.getString("TENSANPHAM");
                           item[2] = rs.getString("THUONGHIEU");
                           item[3] = rs.getDouble("GIANHAP");
                           item[4] = rs.getDouble("GIABAN");
                           item[5] = rs.getInt("SOLUONGCON");
                           tableModel.addRow(item);
                       }
                   } catch (SQLException ex) {
                       System.out.println(ex.toString());
                   }
               } catch (SQLException ex) {
//            Logger.getLogger(QuanLiSanPham.class.getName()).log(Level.SEVERE, null, ex);
System.out.println("kết nối ngu");
               }
           } catch (SQLException ex) {
            Logger.getLogger(QuanLiSanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed

        SanPham sp;

        
        String tensp = txtTensp.getText();
        if (tensp.trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, " Tên sản phẩm còn trống");
            return;
        }
        String thuonghieu = cbbThuongHieu.getSelectedItem().toString();
        if (thuonghieu.trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Thương hiệu còn trống!");
        }
        double gianhap = Double.parseDouble(txtGiaNhap.getText());
        if ((gianhap+"").trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Giá nhập còn trống!");
        }
        double giaban = Double.parseDouble(txtGiaBan.getText());
        if ((giaban+"").trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Giá bán còn trống!");
        }
        int slc = Integer.parseInt(txtSoluongcon.getText());
        
        sp = new SanPham(tensp, thuonghieu, gianhap, giaban, slc);
        dssp.add(sp);
        
        if (new ConnectDB().themSP(sp)) {
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Thêm thất bại");
        }
        getData();
        txtMasp.setText("");
        txtTensp.setText("");
        cbbThuongHieu.setSelectedIndex(10);
        txtGiaNhap.setText("");
        txtGiaBan.setText("");
        txtSoluongcon.setText("");
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
        int d = jTableQlsp.getSelectedRow();
        SanPham sp = dssp.get(d);
        dssp.get(d).setMaSP(Integer.parseInt(txtMasp.getText()));
        dssp.get(d).setTenSP(txtTensp.getText());
        dssp.get(d).setThuongHieu(cbbThuongHieu.getSelectedItem().toString());
        dssp.get(d).setGiaNhap(Double.parseDouble(txtGiaNhap.getText()));
        dssp.get(d).setGiaBan(Double.parseDouble(txtGiaBan.getText()));
        dssp.get(d).setSoLuongcon(Integer.parseInt(txtSoluongcon.getText()));
        
        if (new ConnectDB().suaSP(sp)) {
            JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
            getData();

        } else {
            JOptionPane.showMessageDialog(rootPane, "Sửa thất bại");
        }
        getData();
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        int d = jTableQlsp.getSelectedRow();
        if (d >= 0) {
            SanPham sp = dssp.get(d);
            int op = JOptionPane.showConfirmDialog(rootPane, "Bạn có thực sự muốn xóa", "Xóa sản phẩm", JOptionPane.YES_NO_OPTION);
            if (op == JOptionPane.YES_OPTION) {
                dssp.remove(sp);
            }
            if (new ConnectDB().xoaSP(sp)) {
                JOptionPane.showMessageDialog(rootPane, "Đã xóa sản phẩm " + sp.getTenSP());
                getData();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Xóa thất bại");
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Chưa có sản phẩm để xóa");
        }
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jTableQlspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableQlspMouseClicked

        int d = jTableQlsp.getSelectedRow();
        txtMasp.setText(dssp.get(d).getMaSP()+"");
        txtTensp.setText(dssp.get(d).getTenSP());
        txtGiaNhap.setText(dssp.get(d).getGiaNhap()+"");
        txtGiaBan.setText(dssp.get(d).getGiaBan()+"");
        cbbThuongHieu.setSelectedItem(dssp.get(d).getThuongHieu());
        txtSoluongcon.setText(dssp.get(d).getSoLuongcon()+"");
    }//GEN-LAST:event_jTableQlspMouseClicked

    private void txtTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new frmTrangChuAdmin().setVisible(true);this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonThemPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemPActionPerformed
        String tenNV, tenNcc;
        //int mapn = Integer.parseInt(txtMapn.getText());
        tenNV = cbbNhanVien.getSelectedItem().toString();
        tenNcc = cbbNhaCC.getSelectedItem().toString();
        String sql1 = "select MaNhaCungCap from NhaCungCap where TenNhaCungCap = N'" + tenNcc + "'";
        String sql2 = "select MaNhanVien from NhanVien where TenNhanVien = N'" + tenNV + "'";
        String sql3 = "select sum(tongtien) as thanhtien from ChiTietPhieuNhap where MaPhieuNhap='" + txtMapn.getText() + "'";
        ResultSet rs1 = new ConnectDB().ExcuteQueryGetTable(sql1);
        ResultSet rs2 = new ConnectDB().ExcuteQueryGetTable(sql2);
        int manv = 0, mancc = 0;
        float tongtien = 0;
        try {
            while (rs1.next()) {
                mancc = rs1.getInt("MaNhaCungCap");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            while (rs2.next()) {
                manv = rs2.getInt("MaNhanVien");
            }

        } catch (Exception e) {
        }
        System.out.println("Mã nv"+manv);
        String nl = txtNgayNhap.getText();
        String sql = "insert into PhieuNhap(MaNhanVien,MaNhaCungCap,NgayNhap,TongTien) values ( '" + manv + "','" + mancc + "','" +  nl+ "','"+tongtien+"')";
        new ConnectDB().ExcuteQueryUpdateDB(sql);
        LayDuLieuPhieuNhap();        
    }//GEN-LAST:event_jButtonThemPActionPerformed

    private void txtNgayNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayNhapActionPerformed

    private void jTabbedPaneSanPhamComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPaneSanPhamComponentShown
        LayDuLieuSanPham();
    }//GEN-LAST:event_jTabbedPaneSanPhamComponentShown

    private void jButtonSuaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaPActionPerformed
        String tenNV, tenNcc;
         int maPN = Integer.parseInt(txtMapn.getText());
        tenNV = cbbNhanVien.getSelectedItem().toString();
        tenNcc = cbbNhaCC.getSelectedItem().toString();
        String sql1 = "select MaNhaCungCap from NhaCungCap where TenNhaCungCap = N'" + tenNcc + "'";
        String sql2 = "select MaNhanVien from NhanVien where TenNhanVien = N'" + tenNV + "'";
        
        ResultSet rs1 = new ConnectDB().ExcuteQueryGetTable(sql1);
        ResultSet rs2 = new ConnectDB().ExcuteQueryGetTable(sql2);
        int manv = 0, mancc = 0;
       
        try {
            while (rs1.next()) {
                mancc = rs1.getInt("MaNhaCungCap");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            while (rs2.next()) {
                manv = rs2.getInt("MaNhanVien");
            }

        } catch (Exception e) {
        }
      
        String nl = txtNgayNhap.getText();
        String sql = "update PhieuNhap set MaNhanVien=" + manv + ",MaNhaCungCap=" + mancc + ", where MaPhieuNhap=" + maPN + "";
        new ConnectDB().ExcuteQueryUpdateDB(sql);
        LayDuLieuPhieuNhap();     
    }//GEN-LAST:event_jButtonSuaPActionPerformed

    private void jButtonXoaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaPActionPerformed
        int maPN = Integer.parseInt(txtMapn.getText());
        String sql = "delete PhieuNhap where MaPhieuNhap=" + maPN + "";
        new ConnectDB().ExcuteQueryGetTable(sql);
        LayDuLieuPhieuNhap();
    }//GEN-LAST:event_jButtonXoaPActionPerformed

    private void jButtonThemCtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemCtActionPerformed
        String tensp;
        float tongtien = 0;
        
        int maPN = Integer.parseInt(txtMaPN_CTPN.getText());
        int sl = Integer.parseInt(txtSoLuong.getText());
        tensp = cbbSanPham.getSelectedItem().toString();
        String sql1 = "select gianhap from SanPham where TenSanPham = N'" + tensp + "'";
        String sql2 = "select MaSanPham from SanPham where TenSanPham = N'" + tensp + "'";
        String sql3 = "select sum(tongtien) as thanhtien from ChiTietPhieuNhap where MaPhieuNhap='" +txtMaPN_CTPN.getText() + "'";
        ResultSet rs3 = new ConnectDB().ExcuteQueryGetTable(sql3);
        ResultSet rs1 = new ConnectDB().ExcuteQueryGetTable(sql1);
        ResultSet rs2 = new ConnectDB().ExcuteQueryGetTable(sql2);
        int masp = 0;
        float gia = 0;
        System.out.println(tensp);
        try 
        {
            while (rs1.next()) 
            {

                gia = rs1.getFloat("gianhap");
            }

        } catch (Exception e) 
        {
            e.printStackTrace();
        }

        try {
            while (rs2.next())
            {
                masp = rs2.getInt("MaSanPham");
            }

        } catch (Exception e) 
        {

        }

        try {
            while (rs3.next())
            {
               tongtien = rs3.getFloat("thanhtien");

            }
        } catch (Exception e)
        {
            e.printStackTrace();
        }
        float thanhtien = sl * gia;
        System.out.println("Tổng"+tongtien);
        String sql = "insert into ChiTietPhieuNhap(MaPhieuNhap,MaSanPham,soluong,TongTien) values(  '" + maPN + "','" + masp + "','" + sl + "','" + thanhtien + "')";
        new ConnectDB().ExcuteQueryUpdateDB(sql);
        LayDuLieuChiTietPhieuNhap(txtMaPN_CTPN.getText());
        new ConnectDB().ExcuteQueryUpdateDB("update PhieuNhap set tongtien='" + (tongtien+thanhtien) + "' where MaPhieuNhap='" + txtMaPN_CTPN.getText() + "'");
        LayDuLieuPhieuNhap();
    }//GEN-LAST:event_jButtonThemCtActionPerformed

    private void jTablePhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePhieuNhapMouseClicked
         int vitri = jTablePhieuNhap.getSelectedRow();
        System.out.println(vitri);
        
        txtMapn.setText(jTablePhieuNhap.getValueAt(vitri, 0).toString());
        txtNgayNhap.setText(jTablePhieuNhap.getValueAt(vitri, 3).toString());
        txtTongTien.setText(jTablePhieuNhap.getValueAt(vitri, 4).toString());
        cbbNhanVien.setSelectedItem(jTablePhieuNhap.getValueAt(vitri, 1).toString());
        cbbNhaCC.setSelectedItem(jTablePhieuNhap.getValueAt(vitri, 2).toString());
        txtMaPN_CTPN.setText(jTablePhieuNhap.getValueAt(vitri, 0).toString());
        LayDuLieuChiTietPhieuNhap(jTablePhieuNhap.getValueAt(vitri, 0).toString());
    }//GEN-LAST:event_jTablePhieuNhapMouseClicked

    private void jTableCTPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCTPhieuNhapMouseClicked
        int vitri = jTableCTPhieuNhap.getSelectedRow();
        System.out.println(vitri);
        
        txtMaCtpn.setText(jTableCTPhieuNhap.getValueAt(vitri, 0).toString());
        txtMaPN_CTPN.setText(jTableCTPhieuNhap.getValueAt(vitri, 1).toString());
        txtThanhTien.setText(jTableCTPhieuNhap.getValueAt(vitri, 4).toString());
        txtSoLuong.setText(jTableCTPhieuNhap.getValueAt(vitri, 3).toString());
        cbbSanPham.setSelectedItem(jTablePhieuNhap.getValueAt(vitri, 2).toString());
       
    }//GEN-LAST:event_jTableCTPhieuNhapMouseClicked

    private void jButtonXoaCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaCTActionPerformed
        int sl,mactpn;
        float tongtien = 0;
        mactpn=Integer.parseInt(txtMaCtpn.getText());
        sl = Integer.parseInt(txtSoLuong.getText());
        String tensp = cbbSanPham.getSelectedItem().toString();
        String sql = "select sum(tongtien) as thanhtien from ChiTietPhieuNhap where MaPhieuNhap='" + txtMaPN_CTPN.getText() + "'";
        
//        String sql1="select gianhap from sanpham where TenSanPham=N'"+tensp+"";
        String sql1 = "select gianhap from SanPham where TenSanPham = N'" + tensp + "'";
        ResultSet rs = new ConnectDB().ExcuteQueryGetTable(sql);
        ResultSet rs1=new ConnectDB().ExcuteQueryGetTable(sql1);
        int masp = 0;
        float gia = 0;
        try {
            while (rs.next()) {
                tongtien = rs.getFloat("thanhtien");

            }
        } catch (Exception e) {

        }
        try {
            while (rs1.next()) {
                gia = rs1.getFloat("gianhap");

            }
        } catch (Exception e) {

        }
      
        float thanhtien = sl * gia;
        //System.out.println(""+gia);
        String sql2 = "delete ChiTietPhieuNhap where MaCTPN="+mactpn+"";
        new ConnectDB().ExcuteQueryUpdateDB(sql2);
        System.out.println("Đã sửa Thành Công");
        new ConnectDB().ExcuteQueryUpdateDB("update PhieuNhap set tongtien='" + (tongtien-thanhtien) + "' where MaPhieuNhap='" + txtMaPN_CTPN.getText() + "'");
        LayDuLieuChiTietPhieuNhap(txtMaPN_CTPN.getText());
        LayDuLieuPhieuNhap();
    }//GEN-LAST:event_jButtonXoaCTActionPerformed

    private void jButtonSuaCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaCTActionPerformed
        String tensp;
        float tongtien = 0;
        int maPN = Integer.parseInt(txtMaPN_CTPN.getText());
        int sl =   Integer.parseInt(txtSoLuong.getText());
        tensp = cbbSanPham.getSelectedItem().toString();
        String sql1 = "select gianhap from SanPham where TenSanPham = N'" + tensp + "'";
        String sql2 = "select MaSanPham from SanPham where TenSanPham = N'" + tensp + "'";
        String sql3 = "select sum(tongtien) as thanhtien from ChiTietPhieuNhap where MaPhieuNhap='" + txtMaPN_CTPN.getText() + "'";
        
        ResultSet rs1 = new ConnectDB().ExcuteQueryGetTable(sql1);
        ResultSet rs2 = new ConnectDB().ExcuteQueryGetTable(sql2);
        ResultSet rs3 = new ConnectDB().ExcuteQueryGetTable(sql3);
        int masp = 0;
        float gia = 0;
        System.out.println(tensp);

        try {
            while (rs1.next()) {

                gia = rs1.getFloat("gianhap");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        try {
            while (rs2.next()) {
                masp = rs2.getInt("MaSanPham");
            }

        } catch (Exception e) {

        }

        try {
            while (rs3.next()) {
               tongtien = rs3.getFloat("thanhtien");

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        float thanhtien = sl * gia;
        String sql = "update ChiTietPhieuNhap  set MaPhieuNhap="+maPN+",MaSanPham="+masp+",soluong="+sl+",TongTien="+thanhtien+" where MaCTPN="+txtMaCtpn.getText()+"";
        new ConnectDB().ExcuteQueryUpdateDB(sql);
        LayDuLieuChiTietPhieuNhap(txtMaPN_CTPN.getText());
        new ConnectDB().ExcuteQueryUpdateDB("update PhieuNhap set tongtien='" + tongtien + "' where MaPhieuNhap='" + txtMaPN_CTPN.getText() + "'");
        LayDuLieuPhieuNhap();
    }//GEN-LAST:event_jButtonSuaCTActionPerformed

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
getData();
    }//GEN-LAST:event_btnReloadActionPerformed
    public void getData() {
        dssp = new ConnectDB().getListSP();
        tableSP = (DefaultTableModel) jTableQlsp.getModel();
        tableSP.setRowCount(0);
        for (SanPham sp : dssp) {
            tableSP.addRow(new Object[]{
                sp.getMaSP(),
                sp.getTenSP(),
                sp.getGiaNhap(),
                sp.getGiaBan(),
                sp.getThuongHieu(),
                sp.getSoLuongcon()

            }
            );
        }
    }
    private void LayDuLieuChiTietPhieuNhap(String maPN) {
        String cautruyvan = "select MaCTPN,MaPhieuNhap,SanPham.TenSanPham,SoLuong,TongTien "
                + " from ChiTietPhieuNhap,SanPham where ChiTietPhieuNhap.MaSanPham=SanPham.MaSanPham  and MaPhieuNhap=" + maPN;
        ResultSet rs = new ConnectDB().ExcuteQueryGetTable(cautruyvan);
        Object[] obj = new Object[]{"Mã CTPN", "Mã Phiếu nhập", "Tên Sản Phẩm", "Số Lượng", "Thành tiền"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        jTableCTPhieuNhap.setModel(tableModel);
        try {
            while (rs.next()) {
                Object[] item = new Object[5];
                item[0] = rs.getInt("MaCTPN");
                item[1] = rs.getString("MaPhieuNhap");
                item[2] = rs.getString("TenSanPham");
                item[3] = rs.getString("SoLuong");
                item[4] = rs.getDouble("TongTien");
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }
      private void LayDuLieuPhieuNhap() {
         String sql = "select MaPhieuNhap,NhanVien.TenNhanVien as TenNhanVien,NhaCungCap.TenNhaCungCap as TenNhaCungCap,TongTien,NgayNhap from PhieuNhap,NhaCungCap,NhanVien where PhieuNhap.MaNhaCungCap =NhaCungCap.MaNhaCungCap "
                + "and PhieuNhap.MaNhanVien=NhanVien.MaNhanVien ";
        ResultSet rs = new ConnectDB().ExcuteQueryGetTable(sql);
        Object[] obj = new Object[]{"Mã phiếu nhập", "Tên nhân viên", "Tên NCC", "Ngày Lập", "Tổng tiền"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        jTablePhieuNhap.setModel(tableModel);
        try {
            while (rs.next()) {
                Object[] item = new Object[5];
                item[0] = rs.getInt("MaPhieuNhap");
                item[1] = rs.getString("TenNhanVien");
                item[2] = rs.getString("TenNhaCungCap");
                item[3] = rs.getString("NgayNhap");
                item[4] = rs.getInt("TongTien");
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }

    }

//    public boolean checkmaSp() {
//        for (SanPham sp : dssp) {
//            if (sp.getMaSP().equalsIgnoreCase(txtMasp.getText())) {
//                return false;
//            }
//
//        }
//        return true;
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLiSanPham().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReload;
    private javax.swing.JComboBox<String> cbbNhaCC;
    private javax.swing.JComboBox<String> cbbNhanVien;
    private javax.swing.JComboBox<String> cbbSanPham;
    private javax.swing.JComboBox<String> cbbThuongHieu;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonSuaCT;
    private javax.swing.JButton jButtonSuaP;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonThemCt;
    private javax.swing.JButton jButtonThemP;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JButton jButtonXoaCT;
    private javax.swing.JButton jButtonXoaP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPaneSanPham;
    private javax.swing.JTable jTableCTPhieuNhap;
    private javax.swing.JTable jTablePhieuNhap;
    private javax.swing.JTable jTableQlsp;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtMaCtpn;
    private javax.swing.JTextField txtMaPN_CTPN;
    private javax.swing.JTextField txtMapn;
    private javax.swing.JTextField txtMasp;
    private javax.swing.JTextField txtNgayNhap;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtSoluongcon;
    private javax.swing.JTextField txtTensp;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables

    
}
